services:
  # ---------- Shared datastores ----------
  dynamodb:
    image: amazon/dynamodb-local
    ports: [ "8000:8000" ]
    healthcheck:
      test: [ "CMD-SHELL", "echo > /dev/tcp/localhost/8000" ]
      interval: 3s
      timeout: 2s
      retries: 10

  mysql:
    image: mysql:8.0.36
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leadreach
      MYSQL_USER: lead
      MYSQL_PASSWORD: leadpw
    ports: [ "3306:3306" ]
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  # ---------- Micro-services ----------
  lead-service:
    build:
      context: .
      dockerfile: ./services/lead-service/Dockerfile
    ports: [ "50055:50055" ]
    environment:
      # JDBC settings picked up by Micronaut
      - JDBC_URL=jdbc:mysql://mysql:3306/leadreach
      - JDBC_USER=lead
      - JDBC_PASSWORD=leadpw
      - GRPC_PORT=50055
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 50055 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: on-failure

  enrichment-service:
    build:
      context: .
      dockerfile: ./services/enrichment-service/Dockerfile
    ports: [ "50052:50052" ]
    environment:
      - GRPC_PORT=50052

  outreach-service:
    build:
      context: .
      dockerfile: ./services/outreach-service/Dockerfile
    ports: [ "50053:50053" ]
    environment:
      - GRPC_PORT=50053

  orchestrator:
    build:
      context: .
      dockerfile: ./services/orchestrator/Dockerfile
    ports: [ "50051:50051", "8080:8080" ]
    environment:
      - AWS_REGION=local
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - GRPC_PORT=50051
      - LEAD_SERVICE_HOST=lead-service
      - LEAD_SERVICE_PORT=50055
      - ENRICHMENT_SERVICE_HOST=enrichment-service
      - ENRICHMENT_SERVICE_PORT=50052
      - OUTREACH_SERVICE_HOST=outreach-service
      - OUTREACH_SERVICE_PORT=50053
    depends_on:
      dynamodb:
        condition: service_healthy
      lead-service:
        condition: service_healthy
      enrichment-service:
        condition: service_started
      outreach-service:
        condition: service_started
    restart: on-failure

volumes:
  mysql_data:
