micronaut:
  application:
    name: lead-service
  server:
    port: 8081
  flyway:
    enabled: false
    datasources:
      default:
        enabled: false

datasources:
  default:
    # Use mysql hostname when running in Docker, localhost when running individually
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/leadreach`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:123456}
    driverClassName: com.mysql.cj.jdbc.Driver

jdbi:
  default:
    transaction-handler: jdbc

grpc:
  server:
    port: 50055
