micronaut:
  application:
    name: lead-service
  server:
    port: 50051
  flyway:
    enabled: true
    datasources:
      default:
        enabled: true
        locations: classpath:db/migration

datasources:
  default:
    url: ${JDBC_URL:`jdbc:mysql://localhost:3306/leadreach`}
    username: ${JDBC_USER:root}
    password: ${JDBC_PASSWORD:password}
    driverClassName: com.mysql.cj.jdbc.Driver

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true

grpc:
  server:
    port: 50051
